services:
  - type: web
    name: greenmind-ai
    env: python
    plan: free
    autoDeploy: true
    buildCommand: |
      set -e
      pip install --upgrade pip
      pip install -r requirements.txt

      # ensure target dirs exist
      mkdir -p models/checkpoints
      mkdir -p runs/detect/train/weights

      # --- download your classifier (optional) ---
      if [ -n "$CKPT_URL" ]; then
        echo "[build] Downloading classifier from $CKPT_URL"
        curl -fsSL "$CKPT_URL" -o models/checkpoints/plant_id_resnet18_best.pth
        ls -lh models/checkpoints/plant_id_resnet18_best.pth
      else
        echo "[build] CKPT_URL not set — using file from repo if present"
      fi

      # --- download YOLO weights (optional) ---
      if [ -n "$YOLO_URL" ]; then
        echo "[build] Downloading YOLO from $YOLO_URL"
        curl -fsSL "$YOLO_URL" -o runs/detect/train/weights/best.pt
        ls -lh runs/detect/train/weights/best.pt
      else
        echo "[build] YOLO_URL not set — using file from repo if present"
      fi
    startCommand: gunicorn -w 1 -k gthread -t 180 -b 0.0.0.0:$PORT app.main:app
    healthCheckPath: /health
    envVars:
      # --- Runtime / Python ---
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.10.14

      # --- Local classifier + maps ---
      - key: MODEL_NAME
        value: resnet18
      - key: CKPT_PATH
        value: models/checkpoints/plant_id_resnet18_best.pth
      - key: IDX2_PATH
        value: models/class_maps/idx_to_species.json

      # --- YOLO detector ---
      - key: YOLO_WEIGHTS
        value: runs/detect/train/weights/best.pt
      - key: REQUIRE_DETECT
        value: "1"
      - key: YOLO_CONF
        value: "0.35"
      - key: YOLO_MIN_AREA_FRAC
        value: "0.05"
      - key: YOLO_MAX_CROPS
        value: "5"

      # --- Identification logic thresholds ---
      - key: TOPK
        value: "3"
      - key: CONFIDENCE_THRESHOLD
        value: "0.60"
      - key: MIN_IS_PLANT
        value: "0.60"
      - key: MIN_TOP1_GAP
        value: "0.15"
      # - key: ORGAN_HINT
      #   value: ""   # optional: leaf|flower|fruit

      # --- Facts / timeouts ---
      - key: WIKIPEDIA_TIMEOUT
        value: "10"
      - key: FACTS_CACHE_DIR
        value: ".cache/facts"

      # --- External APIs (set real values in Render dashboard) ---
      - key: PLANT_ID_API_KEY
        sync: false
      - key: PLANT_ID_URL
        value: https://api.plant.id/v3/identification
      - key: PLANTNET_API_KEY
        sync: false
      - key: PLANTNET_URL
        value: https://my-api.plantnet.org/v2/identify/all
      - key: OPENAI_API_KEY
        sync: false

      # --- optional: URLs to download weights at build time ---
      - key: CKPT_URL
        sync: false
      - key: YOLO_URL
        sync: false
