services:
  - type: web
    name: greenmind-ai
    env: python
    plan: free
    autoDeploy: true
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      # --- fetch trained checkpoint if URL is provided ---
      mkdir -p models/checkpoints
      if [ -n "$CKPT_URL" ]; then
        echo "[build] Downloading checkpoint..."
        curl -L "$CKPT_URL" -o models/checkpoints/plant_id_resnet18_best.pth
      else
        echo "[build] CKPT_URL not set; skipping checkpoint download"
      fi
      # --- (optional) fetch YOLO weights if URL provided ---
      if [ -n "$YOLO_URL" ]; then
        mkdir -p runs/detect/train/weights
        echo "[build] Downloading YOLO weights..."
        curl -L "$YOLO_URL" -o runs/detect/train/weights/best.pt
      else
        echo "[build] YOLO_URL not set; skipping YOLO weights"
      fi
    startCommand: gunicorn -w 1 -k gthread -t 180 -b 0.0.0.0:$PORT app.main:app
    healthCheckPath: /health
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.10.14
      - key: MODEL_NAME
        value: resnet18
      - key: CKPT_PATH
        value: models/checkpoints/plant_id_resnet18_best.pth
      - key: IDX2_PATH
        value: models/class_maps/idx_to_species.json
      - key: CKPT_URL
        value:
      - key: YOLO_URL
        value:
      # ---- NEW: Top-2 identification APIs ----
      - key: PLANT_ID_API_KEY
        sync: false
      - key: PLANT_ID_URL
        value: https://api.plant.id/v3/identification
      - key: PLANTNET_API_KEY
        sync: false
      - key: PLANTNET_URL
        value: https://my-api.plantnet.org/v2/identify/all
      - key: OPENAI_API_KEY
        sync: false
      # Optional organ hint
      - key: ORGAN_HINT
        value:
        
      - key: CONFIDENCE_THRESHOLD
        value: "0.50"      # adjust as you like
      - key: MIN_IS_PLANT
        value: "0.50"      # adjust plant/not-plant gate too
      # --- Gating/tuning knobs ---
      - key: CONFIDENCE_THRESHOLD
        value: "0.60"     # try 0.55–0.65 to reduce false positives
      - key: MIN_IS_PLANT
        value: "0.60"     # plant/not-plant gate from Plant.id signal
      - key: MIN_TOP1_GAP
        value: "0.15"     # block if top-1 and top-2 are too close (ambiguous)

      # YOLO hard gate (only used if weights exist)
      - key: REQUIRE_DETECT
        value: "1"        # refuse if no plant-like box is found
      - key: YOLO_CONF
        value: "0.35"     # detector confidence
      - key: YOLO_MIN_AREA_FRAC
        value: "0.05"     # min box area vs image area (e.g., 5%)
      - key: YOLO_ALLOWED
        value: tree,leaf,flower
